# Generated by Django 6.0.1 on 2026-01-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomment',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
