# Generated by Django 6.0.1 on 2026-01-20 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_data', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_chart', to='issues.member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_diagram', to='issues.project')),
            ],
        ),
    ]
